#! /usr/bin/env python3

import serial
import serial.tools.list_ports

port_name = None
for port in serial.tools.list_ports.comports():
    if port.vid == 0x0403 and port.pid == 0x6001:
        port_name = port.device
        break

if port_name is None:
    raise SystemExit("FT232RL not found")

ser = serial.Serial(port_name)
print(not ser.cts)
